apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: s3-output
spec:
  s3:
    aws_key_id:
      valueFrom:
        secretKeyRef:
          name: logging-s3
          key: awsAccessKeyId
    aws_sec_key:
      valueFrom:
        secretKeyRef:
          name: logging-s3
          key: awsSecretAccessKey
    s3_bucket: test
    s3_region: test_region
    s3_endpoint: 'http://minio-service.logging.svc.cluster.local:9000'
    force_path_style: 'true'
    path: logs/${tag}/%Y/%m/%d/
    buffer:
      timekey: 10s
      timekey_wait: 0s
      timekey_use_utc: true
