apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-mc-deployment
spec:
  selector:
    matchLabels:
      app: minio-mc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio-mc
    spec:
      containers:
      - name: minio-mc
        image: minio/mc
        command: ["tail", "-f", "/dev/null"]
